version: '3.7'

services:
  postgres:
    image: postgres
    container_name: autocar_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 41524152sjd_B
      POSTGRES_DB: autocar
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - autocar_network
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: autocar_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sajadbalaniyan.sb@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 41524152sjd_B
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - autocar_network
    restart: unless-stopped
    depends_on:
      - postgres
  redis:
    image: redis:latest
    container_name: autocar_redis
    command: ["redis-server","/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis.conf
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - autocar_network
    restart: unless-stopped
  swagger:
    image: swaggerapi/swagger-ui
    container_name: autocar_swagger
    environment:
      SWAGGER_JSON: /foo/swagger.json
    volumes:
      - ../docs:/foo
    ports:
      - "9090:8080"
    networks:
      - autocar_network
    restart: unless-stopped
volumes:
  postgres:
  pgadmin:
  redis:
  logs:

networks:
  autocar_network:
    driver: bridge

  